version: "2"

services:
  master:
    image: mysql:5.6.42
    ports:
      - "3306:3306"
    volumes:
      - /var/log/mysql
      - ./conf/master:/etc/mysql/conf.d
      - ./initdb/master:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  slave:
    image: mysql:5.7.24
    depends_on:
      - master
    ports:
      - "3307:3306"
    volumes:
      - /var/log/mysql
      - ./conf/slave:/etc/mysql/conf.d
      - ./initdb/slave:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

